# Generated by Django 3.1.4 on 2020-12-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
