# Generated by Django 3.1.4 on 2020-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201203_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Glocery', 'Glocery'), ('Beverages', 'Beverages'), ('Other Categories', 'Other Categories')], default='Glocery', max_length=30),
        ),
    ]
