# Generated by Django 3.1.4 on 2020-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.CharField(choices=[('Cups', 'Cups'), ('Bags', 'Bags')], default='Cups', max_length=10),
        ),
    ]
