# Generated by Django 3.1.4 on 2020-12-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
