# Generated by Django 3.1.4 on 2020-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('vision', models.CharField(blank=True, max_length=300, null=True)),
                ('mission', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
